# Generated by Django 3.2 on 2022-09-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField()),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(db_index=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('description', models.TextField()),
                ('categories_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_categories', to='services.categories')),
                ('room_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_room', to='services.rooms')),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
